config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/405', to: 'errors#internal_server_error', via: :all

  resource :search, only: :show
  # get 'coaching/index'
  # resources :accounts do
  #   resources :tickets do
  #     resources :comments, only: %i[create destroy]
  #     resource :qa, controller: :qualities, except: :index do
  #       member do
  #         get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
  #       end
  #       resources :notes, module: :accounts, only: :create
  #     end
  #   end
# 
  #   # QA is block in this resources.
  #   authenticated :user, ->(user) { user.validate_coaching_access } do
  #     resources :coachings do
  #       resources :notes, module: :accounts, only: :create
  #       member do
  #         get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
  #       end
  #     end
  #   end
# 
  #   post 'join', on: :member
  #   post 'invite', on: :member
  #   delete 'leave', on: :member
  #   delete 'remove', on: :member
  # end

  # Route for the app subdomain
  # constraints subdomain: 'internal' do
    # Add other app-specific routes here
    # root 'accounts#index', as: :account_root
    root 'accounts#index'

    resources :schedules
    resources :accounts do

      get 'settings', to: 'settings#index'
      resources :qa_templates, path: 'settings/qa_templates'
      # resources :coaching_templates, path: 'settings/coaching_templates'

      # resources :tickets do
      #   resources :comments, module: :tickets, only: %i[create destroy]
      #   resource :qa, controller: :qualities, except: :index do
      #     member do
      #       get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
      #     end
      #     resources :notes, module: :accounts, only: :create
      #   end
      # end
      
      resources :qualities, path: 'qa' do
        member do
          get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
        end
        resources :comments, module: :qualities, only: %i[create destroy]
        resources :notes, module: :accounts, only: :create
      end
  
      # QA is block in this resources.
      # authenticated :user, ->(user) { user.validate_coaching_access } do
      #   resources :coachings do
      #     resources :comments, module: :coachings, only: %i[create destroy]
      #     resources :notes, module: :accounts, only: :create
      #     member do
      #       get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
      #     end
      #   end
      # end
  
      post 'join', on: :member
      post 'invite', on: :member
      match 'accept_invitation/:token', to: 'accounts#accept_invitation', as: 'accept_invitation', via: [:get, :post]
      delete 'leave', on: :member
      delete 'remove', on: :member

    end

    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

    # get "/service-worker.js" => "service_worker#service_worker"
    # get "/manifest.json" => "service_worker#manifest"
  # end
  
  # Route for the app subdomain
  constraints subdomain: 'app' do
    # root 'pages#home'
    # Add other app-specific routes here
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
# id                          :bigint                 not null, primary key
# uid                         :string                 not null, unique key
# name                        :string
# slug                        :string
# site                        :integer
# status                      :integer                default(0)
# created_at                  :datetime               not null
# updated_at                  :datetime               not null
#
# Indexes
#
# index_accounts_users_on_account_id_and_user_id      (account_id_and_user_id)
# index_accounts_users_on_user_id_and_account_id      (index_accounts_users_on_user_id_and_account_id)
#
# Foreign keys
#
# fk_rails ... (user_id => users.id)
# fk_rails ... (account_id => accounts.id)
#

class Account < ApplicationRecord
  extend FriendlyId
  Pagy::DEFAULT[:items] = 8

  friendly_id :uid, use: %i[slugged history finders]

  default_scope -> { order(created_at: :asc) }

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :site, presence: true
  after_validation :generated_uid, on: :create
  after_create :create_default_qa_template

  enum :site, %i[sanctum hideout foundry remote]
  enum :status, %i[active inactive pending]

  has_and_belongs_to_many :users
  has_many :account_invitations, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :coachings, dependent: :destroy
  has_many :qualities, dependent: :destroy
  has_many :qa_templates, dependent: :destroy
  has_many :coaching_templates, dependent: :destroy

  def should_generate_new_friendly_id?
    slug.blank? || uid_changed?
  end

  def agent_count
    users.agent.count
  end

  def member?(user)
    users.include?(user)
  end

  def owner?(current_user)
    user_uid == current_user.uid
  end

  def invite_user(email)
    user = User.find_by(email:)

    if user
      return 'User is already a member in this account.' if self.users.include?(user)
      return 'User has a pending invitation' if account_invitations.exists?(user_id: user.id, accepted: false)
    else
      return 'User with the provided email not found.' unless user
    end

    email_invitation(user, generate_invitation_token)
  end

  def self.accept_invitation(token)
    invitation = AccountInvitation.find_by(token:)

    return { success: false, message: 'Invalid invitation link.' } unless invitation
    return { success: false, message: 'User already a member' } if user_already_member?(invitation)
    return { success: false, message: 'Invitation already expired, please create a new one.' } if invitation_expired?(invitation)

    accept_and_process_invitation(invitation)
  end

  private

  # Generate a random number for uuid, since I don't want the field uuid to be empty.
  def generated_uid
    self.uid ||= loop do
      hex = generate_hex
      break hex unless Account.exists?(uid: hex)
    end
  end

  def generate_hex
    SecureRandom.hex(4).to_i(16) % 10_000_000
  end

  def generate_invitation_token
    SecureRandom.urlsafe_base64(32)
  end

  def email_invitation(user, token)
    invitation = account_invitations.new(user:, accepted: false, token:, expires_at: 36.hours.from_now)

    if invitation.save
      AccountInvitationMailer.invite(invitation).deliver_now!

      'User has been invited to the account.'
    else
      'Failed to create an invitation.'
    end
  end

  def self.user_already_member?(invitation)
    invitation.account.users.include?(invitation.user)
  end

  def self.invitation_expired?(invitation)
    invitation.expires_at < Time.now
  end

  def self.accept_and_process_invitation(invitation)
    invitation.update(accepted: true, accepted_at: Time.now)
    invitation.account.users << invitation.user
    { success: true, message: 'Invitation accepted, user added to the account.', account: invitation.account }
  end

  def create_default_qa_template
    return unless qa_templates.empty?
    default_qa_template_data = {
      name: 'Default template',
      published: true,
      metrics: [
        { 'content' => '', 'deduction' => '10', 'metric_name' => 'Grammar' },
        { 'content' => '', 'deduction' => '3', 'metric_name' => 'Punctuation' },
        { 'content' => '', 'deduction' => '8', 'metric_name' => 'Accuracy' }
      ]
    }
    default_qa_template = qa_templates.build(default_qa_template_data)

    if default_qa_template.save
      default_qa_template.create_note(content: 'Default template note content')
    else
      Rails.logger.error("Error creating default QA template: #{default_qa_template.errors.full_messages.join(', ')}")
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :participants, class_name: 'User', join_table: 'schedules_users'

  validates :title, presence: true
  validates :category, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  enum :category, %i[coaching qa meeting]

  has_many :notifications, through: :user, dependent: :destroy
  has_noticed_notifications model_name: 'Notification'
  after_create_commit :notify_recipient
  before_destroy :clean_notifications

  private

  def notify_recipient
    ScheduleNotification.with(schedule: self).deliver_later(participants)
  end

  def clean_notifications
    notifications_as_ticket.destroy_all
  end
end

app/controllers/schedules_controller.rb
require 'pry'

class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: %i[show edit update destroy]
  before_action :mark_notifications_as_read, only: :show
  before_action :restricted, only: %i[new edit destroy]

  def index
    @schedules = current_user.schedules.where(start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week)
  end

  def show; end

  def new
    @schedule = current_user.schedules.build
  end

  def create
    @schedule = current_user.schedules.build(schedule_params)

    if @schedule.save
      user = User.find_by(id: @schedule.user_id)
      @schedule.participants << user
      @schedule.participants << @participants.to_a
      redirect_to root_path, notice: 'New schedule successfully set on calendar.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @schedule.update(schedule_params)
      redirect_to root_path, notice: 'New schedule successfully edited on calendar.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    redirect_to root_path, notice: 'New schedule successfully edited on calendar.' if @schedule.destroy
  end

  private

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:title, :category, :start_time, :end_time, :link, :user_id, participant_ids: [])
  end

  def restricted
    return if current_user.operations? || current_user.admin? || current_user.manager?

    redirect_to schedules_url, alert: "You're not allowed to set a schedule."
  end

  def mark_notifications_as_read
    notification_to_mark_as_read = @schedule.notifications_as_schedule.where(recipient: @schedule.participants)
    notification_to_mark_as_read.update_all(read_at: Time.zone.now) if @schedule.participants
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def schedule_category_color(schedule)
    case schedule.category
    when 'coaching'
      'bg-paleFern'
    when 'qa'
      'bg-paleCoral'
    when 'meeting'
      'bg-gold'
    else
      'bg-coral'
    end
  end
end

app/views/schedules/_form.html.erb
<section class="max-w-screen-lg p-6 mx-auto mt-20">
  <%= form_with(model: @schedule) do |form| %>
    <%= render 'shared/error_messages', object: form.object %>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="mb-6">
      <label class="text-gray-600 mb-3">Title</label>
      <%= form.text_field :title, class:"w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
    </div>

    <div class="mb-6">
      <label class="text-gray-600 mb-3">Category</label>
      <%= form.select :category, Schedule.categories.keys.map { |category| [category.humanize, category]}, {prompt: 'Select a category'}, class:"w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
    </div>

    <div class="grid grid-cols-1 gap-6 mt-4 sm:grid-cols-2 mb-6">
      <div>
        <label class="text-gray-600 mb-3">Start</label>
        <%= form.datetime_field(:start_time, min: DateTime.now.strftime('%Y-%m-%d 00:00:00'), class:"w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md") %>
      </div>

      <div>
        <label class="text-gray-600 mb-3">End</label>
        <%= form.datetime_field(:end_time, min: DateTime.now.strftime('%Y-%m-%d 00:00:00'), class:"w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md") %>
      </div>
    </div>

    <div class="mb-6">
      <label class="text-gray-600 mb-3">Meeting Link</label>
      <%= form.text_field :link, class:"w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
    </div>

    <div class="mb-6">
      <label class="text-gray-600 mb-3">Users</label>
      <%#= form.select(:user_ids, User.all.map { |user| [user.employee_id_and_name, user.id] }, { prompt: 'Select a user', data: { controller: 'slim' } }, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md") %>

      <%= form.select :participant_ids, User.where.not(id: current_user.id).all.map { |user| [user.employee_id_and_name, user.id] }, {include_blank: false}, {multiple: true, data: {controller: 'slim'} } %>

    </div>

    <div class="mt-6">
      <%= form.submit class:"hover:shadow-form cursor-pointer rounded-md bg-paleFern hover:bg-graphite py-3 px-8 text-base font-semibold text-white outline-none" %>
    </div>
  <% end %>
</section>

app/views/schedules/edit.html.erb
<%= provide(:title, "Edit Coaching#{@schedule.id}") %>

<div class="flex flex-col items-start justify-between pb-6 space-y-4 lg:items-center lg:space-y-0 lg:flex-row">
  <ol class="flex flex-wrap pt-1 mr-12 bg-transparent rounded-lg sm:mr-16">
    <li class="leading-normal text-sm">
      <a class="opacity-50 text-slate-700">Pages</a>
    </li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page"><%= link_to "Calendar", root_path %></li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page"><%= link_to @schedule.id, :back%></li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page">Edit</li>
  </ol>

  <div class="space-y-6 md:space-x-2 md:space-y-0">
    <%= link_to @schedule, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, method: :delete, class:"inline-flex items-center justify-center px-4 py-1 space-x-1 bg-coral text-white rounded-md shadow animate-bounce hover:bg-graphite" do %>
      <span>Delete coaching</span>
    <% end if current_user.manager? %>
  </div>
</div>

<%= render "form", account: @account, coaching: @coaching %>

app/views/schedules/index.html.erb
<%= provide(:title, "Schedules") %>

<div class="flex flex-col items-start justify-between pb-6 space-y-4 lg:items-center lg:space-y-0 lg:flex-row">
  <ol class="flex flex-wrap pt-1 mr-12 bg-transparent rounded-lg sm:mr-16">
    <li class="leading-normal text-sm">
      <a class="opacity-50 text-slate-700">Pages</a>
    </li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page">Calendar</li>
  </ol>

  <div class="space-y-6 md:space-x-2 md:space-y-0">
    <%= link_to new_schedule_url, class:"inline-flex items-center justify-center px-4 py-1 space-x-1 bg-paleFern text-white rounded-md shadow animate-bounce hover:bg-graphite" do %>
      <span>Set new schedule</span>
    <% end unless current_user.agent? || current_user.qa? %>
  </div>
</div>

<div class="container mx-auto">
  <%= month_calendar(events: @schedules) do |date, schedules| %>
    <div>
      <%= date.day %>
    </div>

    <div class="bottom h-30 py-1 w-full cursor-pointer overflow-auto" data-controller="popover">
      <% schedules.each do |schedule| %>

        <template data-popover-target="content">
          <div data-popover-target="card" class="popover absolute top-0 left-1/2 transform -translate-x-1/2 z-10 bg-white border border-gray-300 shadow-lg rounded p-4 transition-opacity duration-300 group-hover:opacity-100">
            <div class="p-3">
              <div class="flex">
                <div>
                  <p class="mb-3 text-sm font-normal">
                    <%= schedule.title %>
                  </p>
                  <p class="mb-4 text-sm"><%= schedule.category %></p>
                  <ul class="text-sm">
                    <li class="flex items-center mb-2">
                      <span class="mr-2 font-semibold text-gray-400">
                        <svg class="w-3.5 h-3.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 20">
                          <path
                            stroke="currentColor"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M6.487 1.746c0 4.192 3.592 1.66 4.592 5.754 0 .828 1 1.5 2 1.5s2-.672 2-1.5a1.5 1.5 0 0 1 1.5-1.5h1.5m-16.02.471c4.02 2.248 1.776 4.216 4.878 5.645C10.18 13.61 9 19 9 19m9.366-6h-2.287a3 3 0 0 0-3 3v2m6-8a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                          />
                        </svg>
                      </span>
                      <a href="#" class="text-blue-600 dark:text-blue-500 hover:underline">https://flowbite.com/</a>
                    </li>
                  </ul>
                  <div class="flex mb-3 -space-x-3">
                    <% schedule.participants.each do |participants| %>
                      <%= image_renderer(participants.avatar_url, class: "w-8 h-8 border-2 border-white rounded-full dark:border-gray-800") %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </template>


        <%= link_to schedule,data: { action: "mouseenter->popover#show mouseleave->popover#hide"} do %>
          <div class="event-wrapper flex items-center justify-between <%= schedule_category_color(schedule) %> text-white rounded p-1 text-sm mb-1">
            <div class="event-name font-medium">
              <%= schedule.category.capitalize %>
            </div>
            <div class="text-xs">
              <%= schedule.start_time.strftime('%H:%M') %> - <%= schedule.end_time.strftime('%H:%M') %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/schedules/new.html.erb
<%= provide(:title, "New Coaching") %>

<div class="flex flex-col items-start justify-between pb-6 space-y-4 lg:items-center lg:space-y-0 lg:flex-row">
  <ol class="flex flex-wrap pt-1 mr-12 bg-transparent rounded-lg sm:mr-16">
    <li class="leading-normal text-sm">
      <a class="opacity-50 text-slate-700">Pages</a>
    </li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page"><%= link_to "Calendar", :back %></li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page">New</li>
  </ol>

  <%= link_to :back, class:"hover:shadow-form cursor-pointer rounded-md border-2 border-gray-300 text-graphite hover:bg-graphite py-1 px-4 text-base font-semibold hover:text-white outline-none" do %>
      <span>Cancel</span>
    <% end unless current_user.agent? || current_user.qa? %>
</div>

<%= render "form", coaching: @coaching %>

app/views/schedules/show.html.erb
<%= provide(:title, "Schedule") %>

<div class="flex flex-col items-start justify-between pb-6 space-y-4 lg:items-center lg:space-y-0 lg:flex-row">
  <ol class="flex flex-wrap pt-1 mr-12 bg-transparent rounded-lg sm:mr-16">
    <li class="leading-normal text-sm">
      <a class="opacity-50 text-slate-700">Pages</a>
    </li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page"><%= link_to "Calendar", schedules_url %></li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page"><%= @schedule.title %></li>
  </ol>

  <div class="space-y-6 md:space-x-2 md:space-y-0">
    <%= link_to edit_schedule_url(@schedule), class:"inline-flex items-center justify-center px-4 py-1 space-x-1 bg-gold text-white rounded-md shadow animate-bounce hover:bg-graphite" do %>
        <span>Edit coaching</span>
    <% end if current_user.manager? %>
  </div>
</div>

<article>
  <div class="xl:divide-y xl:divide-gray-200">
    <header class="pt-6 xl:pb-6 border-b border-gray-300">
      <div class="space-y-1 text-center">
        <dl class="space-y-10">
          <div>
            <dt class="sr-only">Published on</dt>
            <dd class="text-base font-medium leading-6 text-gray-500"><time datetime="2023-08-05T00:00:00.000Z">Created at  <%= time_tag @schedule.created_at, 'data-local': 'time-ago' %></time></dd>
          </div>
        </dl>
        <div><h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 sm:text-4xl sm:leading-10 md:text-5xl md:leading-14"><%= @schedule.title %></h1></div>
      </div>
    </header>
    
    <div class="max-w-screen-lg p-6 mx-auto mt-20">
      
      <div class="border-b border-gray-900/10 pb-12">
        <h2 class="text-base font-semibold leading-7 text-gray-900">Coaching Information</h2>
        <p class="mt-1 text-sm leading-6 text-gray-600">Kindly check your email as you have the copy of this coaching log in PDF format.</p>

        <% unless @schedule.link.nil? %>
          Kindly join to this meeting link: <%= @schedule.link %>
        <% end %>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        
          <div class="sm:col-span-3">
            <p class="block text-sm font-medium leading-6 text-gray-900">Inviter</p>
            <p class="border-b py-2 mt-2 text-gray-900 sm:leading-6">
              <%= @schedule.user.employee_id_and_name %>
            </p>
          </div>
      </div>

  </div>
</article>