config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/405', to: 'errors#internal_server_error', via: :all

  resource :search, only: :show
  # get 'coaching/index'
  # resources :accounts do
  #   resources :tickets do
  #     resources :comments, only: %i[create destroy]
  #     resource :qa, controller: :qualities, except: :index do
  #       member do
  #         get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
  #       end
  #       resources :notes, module: :accounts, only: :create
  #     end
  #   end
# 
  #   # QA is block in this resources.
  #   authenticated :user, ->(user) { user.validate_coaching_access } do
  #     resources :coachings do
  #       resources :notes, module: :accounts, only: :create
  #       member do
  #         get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
  #       end
  #     end
  #   end
# 
  #   post 'join', on: :member
  #   post 'invite', on: :member
  #   delete 'leave', on: :member
  #   delete 'remove', on: :member
  # end

  # Route for the app subdomain
  # constraints subdomain: 'internal' do
    # Add other app-specific routes here
    # root 'accounts#index', as: :account_root
    root 'accounts#index'

    resources :schedules
    resources :accounts do

      get 'settings', to: 'settings#index'
      resources :qa_templates, path: 'settings/qa_templates'
      # resources :coaching_templates, path: 'settings/coaching_templates'

      # resources :tickets do
      #   resources :comments, module: :tickets, only: %i[create destroy]
      #   resource :qa, controller: :qualities, except: :index do
      #     member do
      #       get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
      #     end
      #     resources :notes, module: :accounts, only: :create
      #   end
      # end
      
      resources :qualities, path: 'qa' do
        member do
          get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
        end
        resources :comments, module: :qualities, only: %i[create destroy]
        resources :notes, module: :accounts, only: :create
      end
  
      # QA is block in this resources.
      # authenticated :user, ->(user) { user.validate_coaching_access } do
      #   resources :coachings do
      #     resources :comments, module: :coachings, only: %i[create destroy]
      #     resources :notes, module: :accounts, only: :create
      #     member do
      #       get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
      #     end
      #   end
      # end
  
      post 'join', on: :member
      post 'invite', on: :member
      match 'accept_invitation/:token', to: 'accounts#accept_invitation', as: 'accept_invitation', via: [:get, :post]
      delete 'leave', on: :member
      delete 'remove', on: :member

    end

    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

    # get "/service-worker.js" => "service_worker#service_worker"
    # get "/manifest.json" => "service_worker#manifest"
  # end
  
  # Route for the app subdomain
  constraints subdomain: 'app' do
    # root 'pages#home'
    # Add other app-specific routes here
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_account

  def index; end
end

app/views/settings/index.html.erb
<%= content_for(:title, 'Settings') %>

<section class="container px-36 mx-auto my-12">
<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
-->
  <div>
    <div class="space-y-12">
      <div class="sticky top-0 py-12 bg-gray-50 border-b border-gray-300  <%#= horizontal_padding %> z-20">
        <div class="flex justify-between">
        <div class="text-5xl tracking-wide font-serif"><%= @account.name%>'s Settings</div>
      </div>
    </div>

    <div class="container relative flex flex-col justify-between h-full max-w-6xl px-10 mx-auto xl:px-0 mt-5 border-b py-12">
      <h2 class="mb-1 text-3xl font-medium leading-tight text-gray-900">
        Account Information
      </h2>
      <p class="mb-12 text-lg text-gray-500">Here is a few important information of the account.</p>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

        <div class="col-span-full">
          <label for="street-address" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
          <div class="mt-2">
            <input
              type="text"
              name="name"
              value="<%= @account.name %>"
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" disabled
            />
          </div>
        </div>

        <div class="col-span-full">
          <label for="street-address" class="block text-sm font-medium leading-6 text-gray-900">Site</label>
          <div class="mt-2">
            <input
              type="text"
              name="name"
              value="<%= @account.site %>"
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 capitalize" disabled
            />
          </div>
        </div>

        <div class="col-span-full">
          <label for="street-address" class="block text-sm font-medium leading-6 text-gray-900">
            Account ID <span class="text-sm text-gray-500">(Not editable)</span>
          </label>
          <div class="mt-2">
            <input
              type="text"
              name="name"
              value="<%= @account.uid %>"
              class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" disabled
            />
          </div>
        </div>

        <div class="col-span-full">
          <label for="username" class="block text-sm font-medium leading-6 text-gray-900">URL</label>
          <div class="mt-2">
            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
              <span class="flex select-none items-center pl-3 text-gray-500 sm:text-sm">
                <%= "#{base_url}accounts/"%>
              </span>
              <input type="text" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" value="<%= @account.slug %>" disabled>
            </div>
          </div>
        </div>
      </div>

      <div class="mt-6 flex items-center justify-end gap-x-6">
        <p class="text-sm font-medium leading-6 text-gray-900">
          Updated <%= time_tag @account.updated_at, "data-local": "time-ago" %>
        </p>
        <%= link_to "Edit account", edit_account_path(@account), class: "text-orange-700 hover:text-white border border-orange-700 hover:bg-orange-600 focus:ring-4 focus:outline-none focus:ring-orange-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
      </div>
    </div>

    <div class="container relative flex flex-col justify-between h-full max-w-6xl px-10 mx-auto xl:px-0 mt-5 border-b py-12">
      <h2 class="mb-1 text-3xl font-medium leading-tight text-gray-900">Customizeable Templates</h2>
      <p class="mb-12 text-lg text-gray-500">Here is a few of customizeable templates you add or edit in your account.</p>
      <div class="w-full">
          <div class="flex flex-col w-full mb-10 sm:flex-row">
              <div class="w-full mb-10 sm:mb-0 sm:w-1/2">
                  <div class="relative h-full ml-0 mr-0 sm:mr-10 transform transition duration-500 hover:scale-105">
                      <%= link_to account_qa_templates_path do %>
                        <span class="absolute top-0 left-0 w-full h-full mt-1 ml-1 bg-indigo-500 rounded-lg"></span>
                        <div class="relative h-full p-5 bg-white border-2 border-indigo-500 rounded-lg">
                            <div class="flex items-center -mt-1">
                                <h3 class="my-2 ml-3 text-lg font-bold text-gray-800">
                                  QA templates
                                </h3>
                            </div>
                            <p class="mt-3 mb-1 text-xs font-medium text-indigo-500 uppercase">------------</p>
                            <p class="mb-2 text-gray-600">A decentralized application (dapp) is an application built on a
                                decentralized network that combines a smart contract and a frontend user interface.</p>
                        </div>
                      <% end %>
                  </div>
              </div>
              <div class="w-full sm:w-1/2">
                  <div class="relative h-full ml-0 md:mr-10 cursor-not-allowed">
                      <span class="absolute top-0 left-0 w-full h-full mt-1 ml-1 bg-gray-500 rounded-lg"></span>
                      <div class="relative h-full p-5 bg-white border-2 border-gray-500 rounded-lg">
                          <div class="flex items-center -mt-1">
                              <h3 class="my-2 ml-3 text-lg font-bold text-gray-800">
                                Coaching templates
                              </h3>
                          </div>
                          <p class="mt-3 mb-1 text-xs font-medium text-gray-500 uppercase">------------</p>
                          <p class="mb-2 text-gray-600">Web 3.0 is the third generation of Internet services that will
                              focus on understanding and analyzing data to provide a semantic web.</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- source:https://tailwind.besoeasy.com -->

  <div class="container relative flex flex-col justify-between h-full max-w-6xl px-10 mx-auto xl:px-0 mt-5 border-b py-12">
    <h2 class="mb-1 text-3xl font-medium leading-tight text-gray-900">Members</h2>
    <p class="mb-12 text-lg text-gray-500">This section is the section where you can invite user in your account.</p>

    <%= form_with(model: @user, url: invite_account_path(@account), method: :post) do |form| %>
    <div class="flex flex-col items-center w-full">
      <svg xmlns="http://www.w3.org/2000/svg" class="text-indigo-600 h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
      <span class="text-2xl text-gray-800">Assemble Teams</span>
      <span class="text-gray-600">You haven't added any team members to your squad yet.</span>
      <br>
      <div class="flex flex-row w-full mt-4">
        <%= form.text_field :email, name: 'user[email]', placeholder: 'Enter user email', class: 'rounded-md flex-grow border border-gray-400 focus:border-indigo-600' %>
        <%= form.submit 'Send Invitation', class: 'ml-4 px-4 rounded-black border-black border rounded-md bg-green-600 text-white border-0 hover:bg-green-700 transition-all ease-in-out' %>
      </div>
      <br>
      <span class="text-sm text-gray-600 mt-4 w-full align-left tracking-wider">
        TEAM MEMBERS (<%= @account.users.count %>)
      </span>
      <div class="grid grid-cols-2 mt-4 w-full gap-4">
      <% end %>
      <% @account.users.each do |user| %>
        <div class="flex flex-row rounded-full w-full border border-black p-2 gap-4 items-center">
          <div class="flex-shrink w-12 h-12 bg-black rounded-full">
            <%#= image_renderer(user.avatar_url) %>
          </div>
          <div class="flex-grow flex flex-col">
            <span class="text-lg text-gray-800"><%= user.name %></span>
            <span class="text-base text-gray-600"><%#= user.title %> </span>
            <span class="text-base text-gray-400"><%= user.email %> </span>
            <% if user.uid == @account.user_uid %>
              <span>Account owner</span>
              <% end %>
          </div>
          <div class="flex-shrink w-12 h-12 flex justify-center items-center">
            <% if current_user != user %>
              <%#= button_to remove_account_path(@account, email: user.email), data: { method: :delete }, class: "flex items-center space-x-2" do %>

              <%= link_to remove_account_path(@account, email: user.email), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{user.name || user.email}?"}, class: "flex items-center space-x-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink h-8 w-8 hover:text-orange-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
  </div>

</section>


<!-- component -->
<% if ( current_user.manager? && @account.users.include?(current_user) ) || current_user.admin? %>
  <div class="container mx-auto bg-white py-24 px-12 rounded-xl shadow-md">
  <%= form_with(model: @user, url: invite_account_path(@account), method: :post) do |form| %>
    <div class="flex flex-col items-center w-full">
      <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-400 h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
      <span class="text-xl text-gray-800">Assemble Teams</span>
      <span class="text-gray-600">You haven't added any team members to your squad yet.</span>
      <div class="flex flex-row w-full mt-4">
        <%= form.text_field :email, name: 'user[email]', placeholder: 'Enter user email', class: 'rounded-md flex-grow border border-gray-400 focus:border-red-400' %>
        <%= form.submit 'Send Invitation', class: 'ml-4 px-4 rounded-black border-black border rounded-md bg-red-400 text-white border-0 hover:bg-red-600 transition-all ease-in-out' %>
      </div>
      <span class="text-sm text-gray-600 mt-4 w-full align-left tracking-wider">TEAM MEMBERS (<%= @account.users.count %>)</span>
      <div class="grid grid-cols-2 mt-4 w-full gap-4">
      <% end %>
      <% @account.users.each do |user| %>
        <div class="flex flex-row rounded-full w-full border border-black p-2 gap-4 items-center">
          <div class="flex-shrink w-12 h-12 bg-black rounded-full">
            <%= image_renderer(user.avatar_url) %>
          </div>
          <div class="flex-grow flex flex-col">
            <span class="text-lg text-gray-800"><%= user.name %></span>
            <span class="text-base text-gray-600"><%= user.title %> </span>
            <span class="text-base text-gray-400"><%= user.email %> </span>
          </div>
          <div class="flex-shrink w-12 h-12 flex justify-center items-center">
            <% if current_user != user %>
              <%= button_to remove_account_path(@account, email: user.email), method: :delete, class: "flex items-center space-x-2", disabled: !(current_user.manager? || current_user.admin?) do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
<% end %>