config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/405', to: 'errors#internal_server_error', via: :all

  resource :search, only: :show
  # get 'coaching/index'
  # resources :accounts do
  #   resources :tickets do
  #     resources :comments, only: %i[create destroy]
  #     resource :qa, controller: :qualities, except: :index do
  #       member do
  #         get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
  #       end
  #       resources :notes, module: :accounts, only: :create
  #     end
  #   end
# 
  #   # QA is block in this resources.
  #   authenticated :user, ->(user) { user.validate_coaching_access } do
  #     resources :coachings do
  #       resources :notes, module: :accounts, only: :create
  #       member do
  #         get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
  #       end
  #     end
  #   end
# 
  #   post 'join', on: :member
  #   post 'invite', on: :member
  #   delete 'leave', on: :member
  #   delete 'remove', on: :member
  # end

  # Route for the app subdomain
  # constraints subdomain: 'internal' do
    # Add other app-specific routes here
    # root 'accounts#index', as: :account_root
    root 'accounts#index'

    resources :schedules
    resources :accounts do

      get 'settings', to: 'settings#index'
      resources :qa_templates, path: 'settings/qa_templates'
      # resources :coaching_templates, path: 'settings/coaching_templates'

      # resources :tickets do
      #   resources :comments, module: :tickets, only: %i[create destroy]
      #   resource :qa, controller: :qualities, except: :index do
      #     member do
      #       get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
      #     end
      #     resources :notes, module: :accounts, only: :create
      #   end
      # end
      
      resources :qualities, path: 'qa' do
        member do
          get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
        end
        resources :comments, module: :qualities, only: %i[create destroy]
        resources :notes, module: :accounts, only: :create
      end
  
      # QA is block in this resources.
      # authenticated :user, ->(user) { user.validate_coaching_access } do
      #   resources :coachings do
      #     resources :comments, module: :coachings, only: %i[create destroy]
      #     resources :notes, module: :accounts, only: :create
      #     member do
      #       get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
      #     end
      #   end
      # end
  
      post 'join', on: :member
      post 'invite', on: :member
      match 'accept_invitation/:token', to: 'accounts#accept_invitation', as: 'accept_invitation', via: [:get, :post]
      delete 'leave', on: :member
      delete 'remove', on: :member

    end

    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

    # get "/service-worker.js" => "service_worker#service_worker"
    # get "/manifest.json" => "service_worker#manifest"
  # end
  
  # Route for the app subdomain
  constraints subdomain: 'app' do
    # root 'pages#home'
    # Add other app-specific routes here
  end
end

app/models/quality.rb
# == Schema Information
#
# Table name: accounts
#
# id                          :bigint                 not null, primary key
# rating                      :integer
# acknowledgement             string
# date_acknowledged           :boolean               default(false)
# created_at                  :datetime               not null
# updated_at                  :datetime               not null
#
# Indexes
#
# index_qualities_on_ticket_id                         (index_qualities_on_ticket_id)
#
# Foreign keys
#
# fk_rails ... (ticket_id => tickets.id)
#

class Quality < ApplicationRecord
  extend FriendlyId
  Pagy::DEFAULT[:items] = 6
  friendly_id :uid, use: %i[slugged history finders]

  default_scope -> { order(acknowledgement: :asc, created_at: :desc) }
  belongs_to :user
  belongs_to :account

  has_one :note, as: :notable
  accepts_nested_attributes_for :note

  has_many :comments, as: :commentable, dependent: :destroy

validates :link, presence: true
  validates :rating, presence: true,
                     numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  after_validation :generated_uid, on: :create

  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, as: :recipient, dependent: :destroy

  after_create_commit :notify_recipient
  before_destroy :clean_notifications

  def should_generate_new_friendly_id?
     slug.blank? || uid_changed?
  end

  def notify_recipient
    QualityNotification.with(quality: self).deliver_later(user)
  end

  def clean_notifications
    notifications_as_quality.destroy_all
  end

  def self.filter_by_agent_email(agent)
    return all if agent == 'all' || agent.blank?

    user = User.find_by(email: agent)
    where(user:)
  end

  def generated_uid
    self.uid ||= loop do
      hex = generate_hex
      break hex unless Quality.exists?(uid: hex)
    end
  end

  def generate_hex
    SecureRandom.hex(4).to_i(16) % 10_000_000
  end
end

app/controllers/qualities/comments_controller.rb
module Qualities
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = Quality.find(params[:quality_id])
    end
  end
end

app/controllers/qualities_controller.rb
class QualitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quality, only: %i[show edit update destroy acknowledgement]
  before_action :set_account
  # before_action :find_ticket, only: %i[show new create edit update destroy acknowledgement]
  before_action :mark_notifications_as_read, only: :show
  # before_action :authenticate_edit_access, only: %i[new edit]
  before_action :acknowledged?, only: :acknowledgement

  def index
    filtered_qualities = filter

    @pagy, @qualities = if @account.owner?(current_user)
                          pagy(filtered_qualities)
                        else
                          pagy(filtered_qualities.where(user: current_user))
                        end

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @quality.to_json(include: { note: { only: %i[id content] } }) }
      format.pdf do
        render pdf: 'hello-filename', template: 'qualities/quality_pdf', formats: [:html], layout: 'pdf'
      end
    end
  end

  def new
    @note = Note.new
    @quality = Quality.new
    @quality.build_note
  end

  def create
    @quality = @account.qualities.build(quality_params)

    @quality.metrics = populate_metrics

    if @quality.save
      redirect_to account_quality_path(@account, @quality), notice: 'QA saved'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @note_content = @quality.note.content if @quality.note
    @note = @quality.note
  end

  def acknowledgement
    @note_content = @quality.note.content if @quality.note
    @note = @quality.note
  end

  def update
    if @quality.update(quality_params)
      @quality.update(date_acknowledged: Time.now) if @quality.acknowledgement && @quality.date_acknowledged.nil?
      redirect_to account_quality_path(@account, @quality), notice: 'QA saved'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    return flash[:alert] = "You're not authorized to destroy record." unless @account.owner?(current_user)

    @quality.destroy
    redirect_to account_qualities_path(@account),
                notice: 'Record is successfully deleted!'
  end

  private

  def set_quality
    @quality = Quality.find(params[:id])
    redirect_to account_qualities_path, status: :moved_permanently if params[:id] != @quality.slug
  end

  # def find_account
  #   @account = Account.find(params[:account_id])
  # end

  def quality_params
    params.require(:quality).permit(:uid, :slug, :rating, :acknowledgement, :date_acknowledged,
                                    :ticket_id, :account_id, :user_id, :link,
                                    metrics: [], note_attributes: %i[id content])
  end

  def check_if_qa_exist
    return if @ticket.quality.present?

    redirect_back(fallback_location: account_ticket_path(@account, @ticket),
                  alert: 'No QA Check yet.')
  end

  def authenticate_edit_access
    @account = Account.find(params[:account_id])

    return if current_user.qa? || current_user.manager?

    redirect_to account_qualities_path(@account),
                alert: "You're not allowed to create or update a QA record."
  end

  def agent
    @account = Account.find(params[:account_id])

    return if current_user.agent? && @quality.user == current_user

    redirect_to account_quality_path(@account, @quality),
                alert: "You're not suppose to acknowledge this QA record."
  end

  def populate_metrics
    metrics = []
    params[:metric_name]&.each_with_index do |metric_name, index|
      deduction = params[:deduction][index]
      content = params[:content][index]
      metric = { metric_name:, deduction:, content: }
      metrics << metric
    end

    metrics
  end

  def filter
    agent = params[:filter_by]
    @account = Account.find(params[:account_id])

    @account.qualities.filter_by_agent_email(agent)
  end

  def mark_notifications_as_read
    notification_to_mark_as_read = @quality.notifications_as_quality.where(recipient: current_user)
    notification_to_mark_as_read.update_all(read_at: Time.zone.now) if current_user
  end

  def acknowledged?
    if @quality.acknowledgement
      redirect_to account_quality_path(@account, @quality), notice: 'Record already acknowledged.'
    end
  end
end

app/helpers/qualities_helper.rb
module QualitiesHelper
end

app/views/qualities/_form.html.erb
<%= form_with(model: [account, quality], class: "bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl md:col-span-2", data: { controller: "quality-form" }) do |form|  %>
  <%#= render 'shared/error_messages', object: form.object %>
  
  <div class="px-4 py-6 sm:p-8">
    <div class="grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
  
    <%= form.hidden_field :account_id, value: account.id, data: { quality_form_target: "currentAccount" } %>

    <div class="col-span-full">
      <label class="block text-sm font-medium leading-6 text-gray-700">Link</label>
      <%= form.text_field :link, class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
    </div>

    <div class="col-span-full">
      <label class="block text-sm font-medium leading-6 text-gray-700">Agent</label>
      <%= form.collection_select :user_id,
                          @account.users.where.not(id: current_user.id),
                          :id,
                          :email,
                          { prompt: 'Select Agent' },
                          { class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", disabled: @quality.persisted? ? true : false } %>
    </div>

    
    <div class="sm:col-span-3">
      <label class="block text-sm font-medium leading-6 text-gray-700">Rating</label>
      <%= form.number_field :rating, class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", data: { quality_form_target:"ratingInput", disabled: @quality.persisted? } %>
    </div>

    <% if @quality.new_record? %>
      <div class="sm:col-span-3">
        <label class="block text-sm font-medium leading-6 text-gray-700">Type of Templates</label>
        <%= form.collection_select :coaching_template_id,
                                    @account.qa_templates.where(published: true),
                                    :id,
                                    :name,
                                    { prompt: 'Select Template'},
                                    { class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", id: "quality-template-select", data: { quality_form_target: "templateSelect", action: "change->quality-form#updateFormFields" }} %>
      </div>
    <% end %>
  <%# end %>

  <div class="col-span-full">
    <div id="metric-checkboxes" data-quality-form-target="metricCheckboxes"></div>
  </di>
  
  <div id="metric-forms" data-quality-form-target="metricForms" data-controller="nested-form" nested-form-wrapper-selector-value=".nested-form-wrapper"></div>

  <%= form.fields_for(:note, @note) do |note_form| %>
    <div class="col-span-full mb-12">
      <label class="block text-sm font-medium leading-6 text-gray-700">Notes</label>
      <% if quality.persisted? %>
        <% unless @account.owner?(current_user) && !quality.acknowledgement %>
          <div class="trix-editor" data-trix-target="content" contenteditable="false">
            <%= @note.content %>
          </div>
        <% else %>
          <%= note_form.rich_text_area :content, value: @note.content, data: { quality_form_target: "noteField" } %>
        <% end %>
      <% else %>
      <%= note_form.rich_text_area :content, data: { quality_form_target: "noteField"} %>
      <% end %>
    </div>
  <% end %>
  
  <% if quality.persisted? && quality.user == current_user && current_page?(controller: 'qualities', action: 'acknowledgement') %>
    <div class="col-span-full">
      <label class="flex items-center">
        <%= form.check_box :acknowledgement, unchecked_value: false, checked_value: true,class: "w-4 h-4 text-paleFern border-gray-300 rounded focus:ring-paleFern focus:ring-2" %>
        <span class="ml-2 text-md font-bold text-gray-900">Acknowledgement</span>
        <p class="ml-2 text-sm font-normal text-gray-500">(By ticking the check box, you're acknowledging this coaching log.)</p>
      </label>
    </div>
  <% end %>

  </div>
</div>

<div class="flex items-center justify-end gap-x-4 border-t border-gray-900/10 px-4 py-4 sm:px-8 mt-4">
    <% if action_name == 'edit' %>
      <%= link_to "Back", :back, class: "text-sm font-semibold leading-6 text-gray-900 hover:text-gray-500" %>
      <!-- Check turbo_stream destroy later -->
      <%#= link_to account_quality_url(@account), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, method: :delete, class:"flex items-center justify-center w-1/2 px-5 py-2 text-sm tracking-wide text-red-700 hover:text-white border border-red-700 hover:bg-red-600 focus:ring-4 focus:outline-none focus:ring-red-300 rounded-lg shrink-0 sm:w-auto gap-x-2" do %>
        <!--span>Delete</span-->
      <%# end if current_user.manager? %>
    <% else %>
      <%= link_to "Cancel", account_qualities_path(@account), class: "text-sm font-semibold leading-6 text-gray-900 hover:text-gray-500" %>
    <% end %>
    
    <%= form.submit "Save", class: "flex items-center justify-center w-1/2 px-5 py-2 text-sm tracking-wide text-white transition-colors duration-200 bg-green-700 rounded-lg shrink-0 sm:w-auto gap-x-2 hover:bg-green-600 cursor-pointer", onclick: "return confirm('Are you sure you want to save?');" %> 
</div>
<% end %>

<script>
  var isEditing = <%= quality.persisted? ? 'true' : 'false' %>;
</script>

app/views/qualities/_quality.html.erb
<div id="<%= dom_id(quality) %> ">
<tr class="transition-all hover:bg-gray-100 hover:shadow-lg">
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 capitalize hover:text-orange-600">
        <%= link_to quality.uid, account_quality_path(account, quality) %>
      </h2>
    </div>
  </td>
  <%# unless current_user.agent? %>
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div class="flex items-center">
      <div class="flex-shrink-0 w-10 h-10">
        <%= image_renderer(quality.user.avatar_url, class: "w-10 h-10 rounded-full") %>
      </div>
      <div class="ml-4">
        <div class="text-sm font-medium text-gray-900"><%= quality.user.name %></div>
        <div class="text-sm text-gray-500"><%= quality.user.email %></div>
      </div>
    </div>
  </td>
  <%# end %>
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div class="text-sm text-gray-500">
      <%= quality.rating %>
    </div>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <% if quality.acknowledgement? %>
      <span class="inline px-3 py-0.5 text-sm font-normal rounded-full bg-green-100 text-green-800 gap-x-2">
        Acknowledged
      </span>
    <% else %>
      <% if quality.user == current_user && !quality.acknowledgement %>
        <%= link_to acknowledgement_account_quality_url(account, quality), class:"text-orange-950 hover:text-orange-900" do %>
          <svg class="w-5 h-5 mr-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 5V4a1 1 0 0 0-1-1H8.914a1 1 0 0 0-.707.293L4.293 7.207A1 1 0 0 0 4 7.914V20a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5M9 3v4a1 1 0 0 1-1 1H4m11.383.772 2.745 2.746m1.215-3.906a2.089 2.089 0 0 1 0 2.953l-6.65 6.646L9 17.95l.739-3.692 6.646-6.646a2.087 2.087 0 0 1 2.958 0Z"/>
          </svg>
          <p>Acknowledge</p>
        <% end if quality.user == current_user && !quality.acknowledgement %>
      <% else %>
        <span class="inline px-3 text-sm font-normal rounded-full bg-red-100 text-red-800 gap-x-2">
          No Acknowledgement yet.
        </span>
      <% end %>
    <% end %>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div class="text-sm text-gray-500">
      <%= display_acknowledgement_date(quality) %>
    </div>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div class="flex items-center">
      <%= time_tag quality.created_at, "data-local": "time-ago" %>
    </div>
  </td>
  <% if account.owner?(current_user) %>
  <td class="px-6 py-4 text-sm font-medium text-right whitespace-nowrap">
    <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5">
      <div class="flex space-x-4">
        <%= link_to edit_account_quality_url(account, quality), class: "text-orange-600 hover:text-orange-500" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
          </svg>
          <p>Edit</p>
        <% end if account.owner?(current_user) %>

        <%= link_to account_quality_url(account, quality), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, method: :delete, class:"text-red-700 hover:text-red-600" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-1 ml-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
        </svg>
        <p>Delete</p>
      <%end if account.owner?(current_user) %>
      </div>
    </td>
  </td>
  <% end %>
</tr>
</div>

app/views/qualities/index.turbo_stream.erb
<%= turbo_stream.update "qualities", partial: 'qualities/qualities' %>

app/views/qualities/show.html.erb
<%= content_for(:title, "#{@quality.uid}") %>

<section class="container px-36 mx-auto my-12">

<header class="sticky top-0 py-12 bg-gray-50 border-b border-gray-300 z-20">
<div class="flex flex-col items-start justify-between pb-6 space-y-4 lg:items-center lg:space-y-0 lg:flex-row">
  <ol class="flex flex-wrap pt-1 mr-12 bg-transparent rounded-lg sm:mr-16">
    <li class="leading-normal text-sm">
      <a class="opacity-50 text-slate-700"><%= @account.slug %></a>
    </li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/']" aria-current="page"><%= link_to "Quality Assurance", account_qualities_url(@account) %></li>
    <li class="text-sm pl-2 capitalize leading-normal text-slate-700 before:float-left before:pr-2 before:text-gray-600 before:content-['/'] font-medium" aria-current="page"><%= @quality.uid || @quality.slug %></li>
  </ol>

  <div class="space-y-6 md:space-x-2 md:space-y-0">
    <%= link_to edit_account_quality_url(@account, @quality), class:"px-3 py-1 text-xs text-orange-700 hover:text-white border border-orange-700 hover:bg-orange-600 focus:ring-4 focus:outline-none focus:ring-orange-300 font-medium rounded-full" do %>
        <span>Edit <%= @quality.uid %></span>
    <% end if @account.owner?(current_user) %>

    <%= link_to acknowledgement_account_quality_url(@account, @quality), class:"px-3 py-1 text-xs #{legend(@quality.acknowledgement)} font-medium rounded-full #{@quality.acknowledgement? ? 'pointer-events-none' : ''}" do %>
        <span>Acknowledge</span>
    <% end if @quality.user == current_user %>
  </div>
</div>

<div class="text-center -mb-8 mt-8">
  <div>
    <h1 class="text-3xl font-bold leading-9 tracking-tight text-gray-900 sm:text-4xl sm:leading-10 md:text-5xl md:leading-14 tracking-wide">
      <%= @quality.link %>
    </h1>
  </div>
  <dl class="mt-12">
    <div>
      <dt class="sr-only">Published on</dt>
      <dd class="text-base font-medium leading-6 text-gray-500"><time datetime="2023-08-05T00:00:00.000Z">Created <%= time_tag @quality.created_at, 'data-local': 'time-ago' %></time></dd>
    </div>
  </dl>
</div>
</header>

<article>
    <div class="">

      <div class="container relative flex flex-col justify-between h-full max-w-6xl px-10 mx-auto xl:px-0 mt-5 border-b py-12">
        <h2 class="mb-1 text-3xl font-medium leading-tight text-gray-900">
          Details
        </h2>
        <p class="mb-12 text-lg text-gray-500">Kindly check your email as you have the copy of this QA Audit log in PDF format.
        </p>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          
            <div class="sm:col-span-3">
              <p class="block text-sm font-medium leading-6 text-gray-900">Agent</p>
              <p class="border-b py-2 mt-2 text-gray-900 sm:leading-6">
                <%= @quality.user.name || @quality.user.email %>
              </p>
            </div>

            <div class="sm:col-span-3">
              <p class="block text-sm font-medium leading-6 text-gray-900">Account</p>
              <p class="border-b py-2 mt-2 text-gray-900 sm:leading-6 justify-content">
                <%= @quality&.account.name %>
              </p>
            </div>

            <div class="sm:col-span-3">
              <p class="block text-sm font-medium leading-6 text-gray-900">Rating</p>
              <p class="py-2 mt-2 text-gray-900 sm:leading-6 font-bold text-5xl">
                <%= @quality.rating %>
              </p>
            </div>

            <div class="col-span-full">
              <% if @quality.metrics.any? %>
              <p class="block text-lg font-medium leading-6 text-gray-900 mb-6 mt-6">Metrics</p>
                <div class="overflow-hidden border-dashed border-2 border-orange-600 md:rounded-lg p-6">
                  <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                      <tr>
                        <th scope="col" class="px-4 py-3.5 text-md font-normal text-left rtl:text-right text-gray-500">Metric</th>

                        <th scope="col" class="px-4 py-3.5 text-md font-normal text-left rtl:text-right text-gray-500">Deduction</th>

                        <th scope="col" class="px-4 py-3.5 text-md font-normal text-left rtl:text-right text-gray-500">Content</th>

                      </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                      <% @quality.metrics.each do |metric| %> 
                          <tr>
                            <td class="px-4 py-4 text-sm font-normal whitespace-nowrap">
                              <div>
                                <h2 class="font-normal text-xl text-gray-800 capitalize">
                                  <%#= link_to template.name, account_coaching_template_path(template.account, template) %>
                                  <%= metric['metric_name']%>
                                </h2>
                              </div>
                            </td>
                            <td class="px-4 py-4 text-xl whitespace-nowrap">
                              <div class="flex items-center">
                                <%= metric['deduction'] %>
                              </div>
                            </td>

                            <td class="px-4 py-4 text-xl text-wrap">
                              <div class="flex items-center">
                                <%= metric['content'] %>
                              </div>
                            </td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              <% end %>

              <div class="col-span-full border-b">
                <p class="block text-sm font-medium leading-6 text-gray-900 mt-6">Notes</p>
                <p class="px-4 py-4 text-lg text-wrap">
                  <%= @quality.note.content %>
                </p>
              </div>

              <div class="px-48 sm:px-2 md:px-12">
                <div class="flex justify-between items-center mb-6 mt-6">
                  <h2 class="text-lg lg:text-2xl font-medium text-gray-900">Commitment/Comments (<%= @quality.comments.count %>)</h2>
                </div>

                <%= render "comments/form", account: @account, commentable: @quality %>

                <div class="space-y-12">
                  <%= render partial: 'comments/comment', locals: { account: @account, commentable: @quality } %>
                </div>
              </div>
        </div>
      </div>
  </article>
</section>