config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/405', to: 'errors#internal_server_error', via: :all

  resource :search, only: :show
  # get 'coaching/index'
  # resources :accounts do
  #   resources :tickets do
  #     resources :comments, only: %i[create destroy]
  #     resource :qa, controller: :qualities, except: :index do
  #       member do
  #         get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
  #       end
  #       resources :notes, module: :accounts, only: :create
  #     end
  #   end
# 
  #   # QA is block in this resources.
  #   authenticated :user, ->(user) { user.validate_coaching_access } do
  #     resources :coachings do
  #       resources :notes, module: :accounts, only: :create
  #       member do
  #         get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
  #       end
  #     end
  #   end
# 
  #   post 'join', on: :member
  #   post 'invite', on: :member
  #   delete 'leave', on: :member
  #   delete 'remove', on: :member
  # end

  # Route for the app subdomain
  # constraints subdomain: 'internal' do
    # Add other app-specific routes here
    # root 'accounts#index', as: :account_root
    root 'accounts#index'

    resources :schedules
    resources :accounts do

      get 'settings', to: 'settings#index'
      resources :qa_templates, path: 'settings/qa_templates'
      # resources :coaching_templates, path: 'settings/coaching_templates'

      # resources :tickets do
      #   resources :comments, module: :tickets, only: %i[create destroy]
      #   resource :qa, controller: :qualities, except: :index do
      #     member do
      #       get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
      #     end
      #     resources :notes, module: :accounts, only: :create
      #   end
      # end
      
      resources :qualities, path: 'qa' do
        member do
          get 'acknowledgement', to: 'qualities#acknowledgement', as: 'acknowledgement'
        end
        resources :comments, module: :qualities, only: %i[create destroy]
        resources :notes, module: :accounts, only: :create
      end
  
      # QA is block in this resources.
      # authenticated :user, ->(user) { user.validate_coaching_access } do
      #   resources :coachings do
      #     resources :comments, module: :coachings, only: %i[create destroy]
      #     resources :notes, module: :accounts, only: :create
      #     member do
      #       get 'acknowledgement', to: 'coachings#acknowledgement', as: 'acknowledgement'
      #     end
      #   end
      # end
  
      post 'join', on: :member
      post 'invite', on: :member
      match 'accept_invitation/:token', to: 'accounts#accept_invitation', as: 'accept_invitation', via: [:get, :post]
      delete 'leave', on: :member
      delete 'remove', on: :member

    end

    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

    # get "/service-worker.js" => "service_worker#service_worker"
    # get "/manifest.json" => "service_worker#manifest"
  # end
  
  # Route for the app subdomain
  constraints subdomain: 'app' do
    # root 'pages#home'
    # Add other app-specific routes here
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
# id                          :bigint                 not null, primary key
# uid                         :string                 not null, unique key
# name                        :string
# slug                        :string
# site                        :integer
# status                      :integer                default(0)
# created_at                  :datetime               not null
# updated_at                  :datetime               not null
#
# Indexes
#
# index_accounts_users_on_account_id_and_user_id      (account_id_and_user_id)
# index_accounts_users_on_user_id_and_account_id      (index_accounts_users_on_user_id_and_account_id)
#
# Foreign keys
#
# fk_rails ... (user_id => users.id)
# fk_rails ... (account_id => accounts.id)
#

class Account < ApplicationRecord
  extend FriendlyId
  Pagy::DEFAULT[:items] = 8

  friendly_id :uid, use: %i[slugged history finders]

  default_scope -> { order(created_at: :asc) }

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :site, presence: true
  after_validation :generated_uid, on: :create
  after_create :create_default_qa_template

  enum :site, %i[sanctum hideout foundry remote]
  enum :status, %i[active inactive pending]

  has_and_belongs_to_many :users
  has_many :account_invitations, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :coachings, dependent: :destroy
  has_many :qualities, dependent: :destroy
  has_many :qa_templates, dependent: :destroy
  has_many :coaching_templates, dependent: :destroy

  def should_generate_new_friendly_id?
    slug.blank? || uid_changed?
  end

  def agent_count
    users.agent.count
  end

  def member?(user)
    users.include?(user)
  end

  def owner?(current_user)
    user_uid == current_user.uid
  end

  def invite_user(email)
    user = User.find_by(email:)

    if user
      return 'User is already a member in this account.' if self.users.include?(user)
      return 'User has a pending invitation' if account_invitations.exists?(user_id: user.id, accepted: false)
    else
      return 'User with the provided email not found.' unless user
    end

    email_invitation(user, generate_invitation_token)
  end

  def self.accept_invitation(token)
    invitation = AccountInvitation.find_by(token:)

    return { success: false, message: 'Invalid invitation link.' } unless invitation
    return { success: false, message: 'User already a member' } if user_already_member?(invitation)
    return { success: false, message: 'Invitation already expired, please create a new one.' } if invitation_expired?(invitation)

    accept_and_process_invitation(invitation)
  end

  private

  # Generate a random number for uuid, since I don't want the field uuid to be empty.
  def generated_uid
    self.uid ||= loop do
      hex = generate_hex
      break hex unless Account.exists?(uid: hex)
    end
  end

  def generate_hex
    SecureRandom.hex(4).to_i(16) % 10_000_000
  end

  def generate_invitation_token
    SecureRandom.urlsafe_base64(32)
  end

  def email_invitation(user, token)
    invitation = account_invitations.new(user:, accepted: false, token:, expires_at: 36.hours.from_now)

    if invitation.save
      AccountInvitationMailer.invite(invitation).deliver_now!

      'User has been invited to the account.'
    else
      'Failed to create an invitation.'
    end
  end

  def self.user_already_member?(invitation)
    invitation.account.users.include?(invitation.user)
  end

  def self.invitation_expired?(invitation)
    invitation.expires_at < Time.now
  end

  def self.accept_and_process_invitation(invitation)
    invitation.update(accepted: true, accepted_at: Time.now)
    invitation.account.users << invitation.user
    { success: true, message: 'Invitation accepted, user added to the account.', account: invitation.account }
  end

  def create_default_qa_template
    return unless qa_templates.empty?
    default_qa_template_data = {
      name: 'Default template',
      published: true,
      metrics: [
        { 'content' => '', 'deduction' => '10', 'metric_name' => 'Grammar' },
        { 'content' => '', 'deduction' => '3', 'metric_name' => 'Punctuation' },
        { 'content' => '', 'deduction' => '8', 'metric_name' => 'Accuracy' }
      ]
    }
    default_qa_template = qa_templates.build(default_qa_template_data)

    if default_qa_template.save
      default_qa_template.create_note(content: 'Default template note content')
    else
      Rails.logger.error("Error creating default QA template: #{default_qa_template.errors.full_messages.join(', ')}")
    end
  end
end

app/controllers/accounts_controller.rb
require 'pry'

class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, except: %i[index new create accept_invitation]
  before_action :authenticate_account_access, only: :show
  
  def index
    filtered_accounts = filter_by_site

    @pagy, @accounts = pagy(filtered_accounts)
    @total_accounts = Account.count

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show; end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params.merge(user_uid: current_user.uid))

    if @account.save
      
      @account.users << current_user
      redirect_to account_url(@account), notice: 'Account successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @account.update(account_params)
      redirect_to account_settings_url(@account), notice: 'Account successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path, notice: 'Successfully destroyed!'
  end

  def join
    @account.users << current_user
    redirect_to account_url(@account), notice: 'You have joined the account.'
  end

  def leave
    @account.users.delete(current_user)
    redirect_to accounts_url, notice: 'You have left the account.'
  end

  # rubocop:disable Metrics/MethodLength
  def invite
    email = params[:user][:email]
    result = @account.invite_user(email)
    redirect_to account_settings_path(@account), notice: result
  end
  
  def accept_invitation
    result = Account.accept_invitation(params[:token])

    if result[:success]
      redirect_to account_path(result[:account]), notice: result[:message]
    else
      redirect_to accounts_settings_path, alert: result[:message]
    end
  end

  def remove
    email = params[:email]
    @user = User.find_by(email:)

    if @user && @user != current_user
      @account.users.delete(@user)
      redirect_to account_settings_path(@account), notice: 'Successfully removed the user.'
    else
      redirect_to account_settings_path(@account), alert: 'User with the provided email not found.'
    end
  end

  private

  def set_account
    @account = Account.find(params[:id])
    redirect_to @account, status: :moved_permanently if params[:id] != @account.slug
  end

  def account_params
    params.require(:account).permit(:name, :site, :slug)
  end

  def authenticate_account_access
    return if @account.member?(current_user)

    redirect_to accounts_path, alert: "You do not have access to view this account."
  end

  def filter_by_site
    site = params[:filter_by]

    return Account.includes(:users).all if site == 'all' || site.blank?

    Account.includes(:users).where(site:).all
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def require_kpi(account)
    account.enable_kpi ? 'This account does have KPI.' : "This account doesn't require KPI."
  end

  def site_with_color(account)
    color_classes = {
      hideout: 'bg-blue-100 text-blue-800',
      sanctum: 'bg-green-100 text-green-800',
      foundry: 'bg-indigo-100 text-indigo-800',
      remote: 'bg-pink-100 text-pink-800'
    }

    site_name = account.site.to_s.humanize
    color_class = color_classes[account.site&.to_sym] || ''

    content_tag(:div, site_name, class: "inline px-3 py-1 text-sm font-normal rounded-full #{color_class} gap-x-2")
  end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id(account) %>">
  <div class="flex flex-col flex-[1_0_0%] bg-white border rounded-lg">
    <%= image_tag "https://assets-global.website-files.com/64149f79022d0c3ed8ce46e9/64340a48e4ece4230ad42755_SupportNinjas-Brand-Refresh.jpg", class: "w-full h-auto sm:rounded-se-none", alt: "Image" %>
    <div class="p-4 flex-2 md:p-5">
      <div class="flex items-center space-x-1 rtl:space-x-reverse mb-2">
        <h3 class="text-lg font-semibold text-gray-800 hover:text-green-700">
          <%= link_to account.name, account_path(account) %>
        </h3>
        <p class="text-sm text-medium tracking-wide">(#<%= account.uid %>)</p>
      </div>
      <div class="flex -space-x-2">
        <% account.users.limit(8).each do |user| %> 
          <%= image_renderer(user.avatar_url, class: 'w-10 h-10 border-2 border-white rounded-full border-gray-800') %> 
        <% end %> 
        <% if account.users.count > 8 %>
          <p class="flex items-center justify-center w-10 h-10 text-xs font-medium text-white bg-gray-700 border-2 border-white rounded-full hover:bg-gray-600 dark:border-gray-800"><%= account.users.count - 8%></p>
        <% end %>
    </div>
    </div>
    <div class="p-4 border-t sm:px-5">
      <p class="text-xs text-gray-500">
        Created

        <%= time_tag account.created_at, "data-local": "time-ago" %>
      </p>
    </div>
  </div>
</div>

app/views/accounts/_accounts.html.erb
<div id="accounts">
  <div class="grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-3">

    <% current_user.accounts.each do |account| %>
      <%= render 'account', account: account %>
    <% end %>
    
  </div>  
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl md:col-span-2") do |form| %>
  <div class="px-4 py-6 sm:p-8">
    <div class="grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-8">
      
      <div class="col-span-full">
        <%= form.label :name, class: "block text-sm font-medium leading-6 text-gray-700" %>
        <div class="mt-2">
          <%= form.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class='col-span-full'>
        <%= form.label :site, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= form.select :site, Account.sites.keys.map { |site| [site.humanize, site]}, { prompt: "Select a site" }, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
      </div>

      <% if action_name == 'edit' %>
        <div class="col-span-full">
          <%= form.label :slug, "URL", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <div class="mt-2">
            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
              <span class="flex select-none items-center pl-3 text-gray-500 sm:text-sm"><%= base_url %></span>
              <%= form.text_field :slug, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>


    <div class="flex items-center justify-end gap-x-6 border-t border-gray-900/10 px-4 py-4 sm:px-8 mt-4">
    <% if action_name == 'edit' %>
      <%= link_to "Back", :back, class: "text-sm font-semibold leading-6 text-gray-900 hover:text-gray-500" %>
    <% else %>
      <%= link_to "Cancel", accounts_path, class: "text-sm font-semibold leading-6 text-gray-900 hover:text-gray-500" %>
    <% end %>
    

    <%= form.submit "Create account", class: "flex items-center justify-center w-1/2 px-5 py-2 text-sm tracking-wide text-white transition-colors duration-200 bg-green-700 rounded-lg shrink-0 sm:w-auto gap-x-2 hover:bg-green-600", onclick: "return confirm('Are you sure you want to save?');" %> 
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= content_for(:title, "Edit account") %>
<div class="container my-12 mx-auto px-4 md:px-12">
  <div class="space-y-10 divide-y divide-gray-900/10">
    <div class="grid grid-cols-1 gap-x-8 pt-10 md:grid-cols-3">
      <div class="px-4 sm:px-0">
        <h2 class="text-base font-semibold leading-7 text-gray-900">Editing <%= @account.name %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-600">
          Make some selections, fill in some boxes, and go live in minutes.
        </p>
         <p class="mt-4">
            <%= render 'shared/error_messages', object: @account %>
         </p>
      </div>  

      <%= render "form", account: @account %>
    
    </div>
  </div>
  </div>
</div>

app/views/accounts/index.html.erb
<section class="container px-36 mx-auto my-12">
<%if current_user.accounts.empty? %>

  <% if current_user.created_at < 12.hours.ago %>
  <div class="max-w-4xl mx-auto px-10 py-4 bg-white rounded-lg shadow-lg">
    <div class="flex flex-col items-center justify-center py-12">
      <img src="https://cdn-icons-png.flaticon.com/128/907/907717.png" alt="Welcome Icon" class="w-24 h-24 mb-4">
      <h2 class="text-3xl font-semibold mb-2">Welcome to Ninjafied!</h2>
      <p class="text-gray-600 text-center text-lg leading-relaxed">Start your journey with us by exploring the amazing
        features we have to offer:</p>
      <ul class="mt-4 text-gray-600 text-base leading-relaxed">
        <li class="mb-2"><span class="text-green-500">✔</span> Quality Assurance and templates</li>
        <li class="mb-2"><span class="text-green-500">✔</span> Coaching log and templates</li>
        <li class="mb-2"><span class="text-green-500">✔</span> KB articles.</li>
        <li class="mb-2"><span class="text-green-500">✔</span> Unified efficiency tools.</li>
      </ul>
      <em class="mt-12 text-gray-600 text-center text-lg leading-relaxed">Kindly check your email if someone invited you, or go manage your own account.
      </em>
    <%= link_to "Get Started", new_account_path, class: "mt-6 px-6 py-2 bg-blue-500 focus:outline-none text-white bg-green-700 hover:bg-green-600 focus:ring-4 focus:ring-green-700 font-medium rounded-md text-sm cursor-pointer" %>
    </div>
  </div>
  <% else %>
  <div class="max-w-2xl p-12 mx-auto">
    <%= image_tag "empty_state/umbrella.svg", class: "mx-auto h-full" %>
    <div class="-mt-16">
    <h2 class="mt-2 text-lg font-semibold text-center text-gray-800">
      You don't have an account yet.
    </h2>
    <p class="mt-1 text-center text-gray-600">
      Kindly check your email if someone invited you, or go manage your own account.
    </p>
    <div class="flex flex-col items-center justify-center mt-4 space-y-1 md:flex-row md:space-y-0 md:space-x-1">
    <%= link_to "Add account", new_account_path, class: "focus:outline-none text-white bg-green-700 hover:bg-green-600 focus:ring-4 focus:ring-green-700 font-medium rounded-md text-sm px-5 py-2.5 me-2 mb-2 cursor-pointer" %>
    </div>
  </div>
  <% end %>
<% else %>
  <div class="sm:flex sm:items-center sm:justify-between mb-6">
    <div>
      <div class="flex items-center gap-x-3">
        <h2 class="text-lg font-medium text-gray-800">Accounts</h2>
        <span class="px-3 py-1 text-xs text-orange-700 hover:text-white border border-orange-700 hover:bg-orange-600 focus:ring-4 focus:outline-none focus:ring-orange-300 font-medium rounded-full">
          <%= current_user.accounts.count %> accounts
        </span>
      </div>
      <p class="mt-1 text-sm text-gray-500">These accounts are currently active.</p>
    </div>
    <div class="flex items-center mt-4 gap-x-3">
      <%= link_to new_account_path, class:"flex items-center justify-center w-1/2 px-5 py-2 text-sm tracking-wide text-white transition-colors duration-200 bg-green-700 rounded-md shrink-0 sm:w-auto gap-x-2 hover:bg-green-600" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Add account</span>
      <% end %>
    </div>
  </div>
    
  <%= render "accounts" %>
  <%#= render "shared/pagy" %>
<% end %>
</section>

app/views/accounts/index.turbo_stream.erb
<%= turbo_stream.update "accounts", partial: 'accounts/accounts' %>

app/views/accounts/new.html.erb
<%= content_for(:title, "Create account") %>

<div class="container my-12 mx-auto px-4 md:px-12">
  <div class="space-y-10 divide-y divide-gray-900/10">
    <div class="grid grid-cols-1 gap-x-8 pt-10 md:grid-cols-3">
      <div class="px-4 sm:px-0">
        <h2 class="text-base font-semibold leading-7 text-gray-900">Create a new account</h2>
        <p class="mt-1 text-sm leading-6 text-gray-600">
          Make some selections, fill in some boxes, and go live in minutes.
        </p>
         <p class="mt-4">
            <%= render 'shared/error_messages', object: @account %>
         </p>
      </div>  

      <%= render "form", account: @account %>
    
    </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<%= content_for(:title, "#{@account.name}") %>

<section>
  <div class="relative px-8 py-12 mx-auto md:px-12 lg:px-32 max-w-7xl lg:py-24">
    <div class="text-center max-w-xl mx-auto">
      <h1 class="text-8xl font-semibold font-display text-graphite sm:text-6xl text-balance font-serif">
        <%= @account.name %>
      </h1>
      <p class="text-balance mt-4 text-slate-500">
        This is where you'll manage your account.
      </p>
      <div class="flex flex-wrap items-center justify-center mt-8">
        <div>
          <label for="search" class="sr-only">Quick search</label>
          <div class="relative flex items-center">
            <input
              class="w-full h-10 px-4 py-2 placeholder-slate-300 duration-200 ring-1 ring-inset border-transparent ring-white/10 rounded-lg appearance-none bg-slate-50 focus:border-slate-300 focus:outline-none focus:ring-slate-300 duration-500 sm:text-sm text-blue-950 block pr-14"
              id="search"
              name="search"
              type="text"
              placeholder="Search..."
              aria-label="Search"
            />
            <div class="flex absolute inset-y-0 pr-1.5 py-1.5 right-0"><kbd class="items-center inline-flex border-slate-200 font-sans px-0.5 rounded text-blue-950 text-xs">⌘K</kbd></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="container px-36 mx-auto -mt-12">
<div class="-mx-4 flex flex-wrap p-8">
  <div class="w-full px-4 md:w-1/2 lg:w-1/3">
    <%= link_to account_qualities_path(@account) do %>
    <div class="mb-9 rounded-xl py-8 px-7 shadow-md transition-all hover:shadow-lg sm:p-9 lg:px-6 xl:px-9 transform transition duration-500 hover:scale-105 border border-gray-400">
      <div class="mx-auto mb-7 inline-block">
        <%= image_tag "svg/paper-clip.svg" %>
      </div>
      <div>
        <h3 class="mb-4 text-xl font-bold text-black sm:text-2xl lg:text-xl xl:text-2xl">
          Quality Assurance
        </h3>
        <p class="text-base font-medium text-body-color">
          This is where you can view, add, and acknowledge QA audits in the account.
        </p>
      </div>
    </div>
    <% end %>
  </div>

  <div class="w-full px-4 md:w-1/2 lg:w-1/3">
    <%= link_to "#" do %>
    <div class="mb-9 rounded-xl py-8 px-7 shadow-md transition-all hover:shadow-lg sm:p-9 lg:px-6 xl:px-9 border border-gray-200 bg-gray-100 cursor-not-allowed">
      <div class="mx-auto mb-7 inline-block">
        <svg class="w-auto h-16 text-paleFern -mb-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="53" height="53" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M16 19h4a1 1 0 0 0 1-1v-1a3 3 0 0 0-3-3h-2m-2.236-4a3 3 0 1 0 0-4M3 18v-1a3 3 0 0 1 3-3h4a3 3 0 0 1 3 3v1a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1Zm8-10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
        </svg>
      </div>
      <div>
        <h3 class="mb-4 text-xl font-bold text-black sm:text-2xl lg:text-xl xl:text-2xl">
          Coaching
        </h3>
        <p class="text-base font-medium text-body-color">
          This is where you can view, add, and acknowledge Coaching in the account.
        </p>
      </div>
    </div>
    <% end %>
  </div>  

  <div class="w-full px-4 md:w-1/2 lg:w-1/3">
    <%= link_to account_settings_path(@account) do %>
    <div class="mb-9 rounded-xl py-8 px-7 shadow-md transition-all hover:shadow-lg sm:p-9 lg:px-6 xl:px-9 transform transition duration-500 hover:scale-105 border border-gray-400">
      <div class="mx-auto mb-7 inline-block">
      <svg class="w-auto h-14 text-paleFern" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7.75 4H19M7.75 4a2.25 2.25 0 0 1-4.5 0m4.5 0a2.25 2.25 0 0 0-4.5 0M1 4h2.25m13.5 6H19m-2.25 0a2.25 2.25 0 0 1-4.5 0m4.5 0a2.25 2.25 0 0 0-4.5 0M1 10h11.25m-4.5 6H19M7.75 16a2.25 2.25 0 0 1-4.5 0m4.5 0a2.25 2.25 0 0 0-4.5 0M1 16h2.25"/>
      </svg>
      </div>
      <div>
        <h3 class="mb-4 text-xl font-bold text-black sm:text-2xl lg:text-xl xl:text-2xl">
          Account Settings
        </h3>
        <p class="text-base font-medium text-body-color">
          This is where you can add, edit, and remove users. QA and Coaching Templates.
        </p>
      </div>
    </div>
    <% end %>
  </div>
</div>
</section>